---
- name: start redis cluster
  command: "ruby redis-trib.rb create --replicas 1 {{redis_node[0]}}:6379 {{redis_node[0]}}:6380 {{redis_node[1]}}:6379 {{redis_node[1]}}:6380 {{redis_node[2]}}:6379 {{redis_node[2]}}:6380" 
  args:
    chdir: /redis 